Include time.h in avg.c and avg_all.c to fix implicit declaration warning
Both of these files were missing the time.h header, which was causing the
following error message on compilation:

avg.c: In function ‘main’:
avg.c:44:9: warning: implicit declaration of function ‘time’ [-Wimplicit-function-declaration]
   srand(time(NULL));
         ^